### ISSUE TITLE
无法使用，麻烦大佬看看

### ISSUE THREAD

**Issue by zhtyirg3** [assassingyk/novel_ai_kai#1]
大佬，我想问下，添加插件后，在__bot__py 添加 novel_ai_kai 后，机器人毫无反应，在群发送设置API也是没反应，是怎么回事？

**Comment by assassingyk** [comment]
![2QR `J6@AO}7DI6VP)YZ{K8](https://user-images.githubusercontent.com/55473115/144160245-b74160dd-117e-4182-a7a8-847ca3aa0cc7.jpg)

**Comment by zhtyirg3** [comment]
> ![2QR `J6@AO}7DI6VP)YZ{K8](https://user-images.githubusercontent.com/55473115/144160245-b74160dd-117e-4182-a7a8-847ca3aa0cc7.jpg)

不是，关键是后台没有错误日志，连显示都没有，__bot__py 里是添加 novel_ai_kai ，还是添加novel就可以?

**Comment by assassingyk** [comment]
机器人启动时有没有success import 这个module？发送设置API关键词后有没有triggered 提示？这不都是日志的一部分吗...

__bot__py 添加的是module里面的文件夹名，添加的不对理论上机器人根本启动不了，初始化阶段就报FileNotFoundError跳出了，基本不可能是这方面的问题

**Comment by zhtyirg3** [comment]
> 机器人启动时有没有success import 这个module？发送设置API关键词后有没有triggered 提示？这不都是日志的一部分吗...
> 
> __bot__py 添加的是module里面的文件夹名，添加的不对理论上机器人根本启动不了，初始化阶段就报FileNotFoundError跳出了，基本不可能是这方面的问题

是成功的，对了，是LINUX系统。
<img width="436" alt="8a1f1a72cfef12c84a1caec3631afdb" src="https://user-images.githubusercontent.com/55908974/144163393-17529de0-7efe-4afc-ab0e-f21b94375ee5.png">
<img width="583" alt="aa8f86559572eb2958690aaeee3bc9a" src="https://user-images.githubusercontent.com/55908974/144163522-9023c9e5-df6e-4148-a1d4-9da7cf6d1bc6.png">

**Comment by assassingyk** [comment]
![0{111SOD%PQZ9O(D@WEC2UB](https://user-images.githubusercontent.com/55473115/144163696-cc5f8aee-c55b-4ff7-a9b1-843d91541332.jpg)
有triggered但没反应也没报错，那就是你根本没开这个插件
我写了enable_on_default=False来着
不信你lssv看看.jpg

**Comment by zhtyirg3** [comment]
> ![0{111SOD%PQZ9O(D@WEC2UB](https://user-images.githubusercontent.com/55473115/144163696-cc5f8aee-c55b-4ff7-a9b1-843d91541332.jpg) 有triggered但没反应也没报错，那就是你根本没开这个插件 我写了enable_on_default=False来着 不信你lssv看看.jpg

![image](https://user-images.githubusercontent.com/55908974/144164475-4fcbadfd-f7b8-4778-8c8f-7e0565ff6cc8.png)
啊这

**Comment by zhtyirg3** [comment]
![image](https://user-images.githubusercontent.com/55908974/144166230-964536c3-65cb-4c39-9e15-4da949d72a00.png)
好像还是不行

**Comment by zhtyirg3** [comment]
> ![0{111SOD%PQZ9O(D@WEC2UB](https://user-images.githubusercontent.com/55473115/144163696-cc5f8aee-c55b-4ff7-a9b1-843d91541332.jpg) 有triggered但没反应也没报错，那就是你根本没开这个插件 我写了enable_on_default=False来着 不信你lssv看看.jpg

![image](https://user-images.githubusercontent.com/55908974/144166928-20c0ec6f-bea9-4319-95c7-c76ceea65177.png)
好像还是没反应，是指令错了吗

**Comment by assassingyk** [comment]
是指令错了（即答）
续写是only_to_me的，你得在前面加机器人昵称或者at机器人……
看来readme还是得写更详细一点
毕竟不能要求所有人都读源码.jpg

**Comment by zhtyirg3** [comment]
> 是指令错了（即答） 续写是only_to_me的，你得在前面加机器人昵称或者at机器人…… 看来readme还是得写更详细一点 毕竟不能要求所有人都读源码.jpg

确实，我也是刚接触，不是很懂，谢谢大佬

**Comment by zhtyirg3** [comment]
> 是指令错了（即答） 续写是only_to_me的，你得在前面加机器人昵称或者at机器人…… 看来readme还是得写更详细一点 毕竟不能要求所有人都读源码.jpg

还有一个想请教一下，就是能继续续写前面的内容吗，每次都复制前面的内容太麻烦了

**Comment by assassingyk** [comment]
每次提交给彩云小梦后写出来的内容长度基本是固定的，现在的默认效果就是进行了3次迭代提交。
你可以自己设置更大的迭代次数来一次性续写出更长的内容，上限5也可以自己改源码调整。
不过迭代次数太多短时间提交太多次不知道会不会被ban，要动建议自己修下源码每次提交前sleep时间拉长一点什么的
