### ISSUE TITLE
发生错误：账号不存在，请更换apikey！

### ISSUE THREAD

**Issue by doiss** [assassingyk/novel_ai_kai#2]
@assassingyk 大佬这个怎么搞，key是对的，账号也是对的

**Comment by assassingyk** [comment]
错误类型判定是根据返回的status code判断的，除非彩云小梦那边改了返回格式，不然应该还是你key有问题

建议换个账号换个key试一下

**Comment by doiss** [comment]
好的，我试试去

**Comment by doiss** [comment]
就这刚才，我发现了一个严重的问题。。。。。我好像就一个手机号qaq

**Comment by assassingyk** [comment]
试了下，好像还真是彩云小梦那边改了post格式……那可能很多部分要重新写了

**Comment by assassingyk** [comment]
已修复
